### ISSUE TITLE
rename repo to include name SQLAlchemy 

### ISSUE THREAD

**Issue by clach04** [ActianCorp/sqlalchemy-ingres#16]
Check list:

- [x] rename repo from https://github.com/ActianCorp/ingres_sa_dialect to https://github.com/ActianCorp/sqlalchemy-ingres - GitHub will then handle redirects
- [x] rename component in setup.py (etc.) in python package metadata
- [x] post to PyPi https://github.com/ActianCorp/sqlalchemy-ingres/issues/11 - https://pypi.org/project/sqlalchemy-ingres/

needs some thought.

Would then differ from https://pypi.org/project/ingres_sa_dialect/ (which is too old to be useful as of 2024-01).

We could just resume ownership, the owner address is an Ingres address (i.e. no need to go through https://pypi.org/help/#request-ownership if we coordinate with IT).

**Comment by clach04** [comment]
@hab6 I'm thinking we pull the trigger on this. With GItHub, any old refs will redirect if the old URL is used.

**Comment by hab6** [comment]
@clach04 I can see a number of potential related activities (as you imply), such as more frequent drops of the Ingres dialect on https://pypi.org/project/ingres_sa_dialect/. Are you thinking we could have IT redirect the existing email address appropriately instead of updating the contact information on that page?

Thoughts on a new repo name?  In looking at other SQLAlchemy dialects on https://pypi.org/, most follow this simple naming convention: **sqlalchemy-(vendor/db)**. So I guess **`sqlalchemy_ingres`** (without a `-dialect` suffix)?

**Comment by clach04** [comment]
@hab6 good catch on naming, from https://pypi.org/search/?q=sqlalchemy lookslike we should go with hypen as you noted.

So `sqlalchemy-ingres` is the logical rename. Alternative would be `sqlalchemy-actian` which is a bit confusing when Actian has a number of different backends:
* ingres / actian-x
* vector
* actian data platform
* zen
* (HCL) OneDB
* NoSQL

**Comment by hab6** [comment]
Closing issue since this is completed.

Actian repository renamed to [sqlalchemy-ingres](https://github.com/ActianCorp/sqlalchemy-ingres)
PyPI package renamed to [sqlalchemy-ingres](https://pypi.org/project/sqlalchemy-ingres/)
